source 'https://github.com/CocoaPods/Specs.git'

target 'TTCustomCallout', :exclusive => true do
  pod "TTCustomCallout", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "TTCustomCallout", :path => "../"

  
end
